#!/bin/bash

BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[0;35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
Xark='\e[0m'
r="\033[1;91m"
BG_BLU="\033[44;1m" # BG BIRU
GREN="\033[92m"
clear

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/titis69/permission/main/sccoba"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            \033[91;1mPERMISSION DENIED !\033[0m"
    echo -e "   \033[0;33mYour VPS\033[0m $ipsaya \033[0;33mHas been Banned\033[0m"
    echo -e "     \033[0;33mBuy access permissions for scripts\033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
clear

function xVMESS() {
  echo -e     " ${BG_BLU}               XRAY VMESS              ${Xark} "
}

# . 1
function Create_Account() {
  add-tro
}
# . 2
function Create_Trial() {
  trial-tro
}
# . 3
function Delete_Account() {
  del-tro
}
# . 4
function List_Member() {
  member-tro
}
# . 5
function Renew_Account() {
  renew-tro
}
# . 6
function Changes_Limit() {
  ganti-ip-trojan
}

# . 11
function Changes_Limit_Quota() {
  trojan-qouta
}
# . 7 
function Check_Account() {
  cek-tro
}
# . 8 
function Check_Details_Account() {
  check-tro
}

# . 9
function Lock_Account() {
  lock-tr
}

# . 10
function Unlock_Account() {
  unlock-tr
}

# . 11
function Recovery_Trojan() {
  recover-tr
}


# . Daftar Menu Vmess
function Menu_Features() {
echo -e " \033[96;1m╭════════════════════════════════════════════════════╮"
echo -e " \033[96;1m│\e[0m                   \033[1;37mTROJAN PANEL MENU                \e[96;1m│\e[0m"
echo -e " \033[96;1m╰════════════════════════════════════════════════════╯"
echo -e " \033[96;1m╭════════════════════════════════════════════════════╮"
echo -e " \033[96;1m│ $NC \033[1;37m[\033[96;1m01\033[1;37m] \033[96;1m• \033[1;37mADD AKUN         \033[1;37m[\033[96;1m06\033[1;37m] \033[96;1m• \033[1;37mCEK USER CONFIG    \033[96;1m│ $NC"
echo -e " \033[96;1m│ $NC \033[1;37m[\033[96;1m02\033[1;37m] \033[96;1m• \033[1;37mTRIAL AKUN       \033[1;37m[\033[96;1m07\033[1;37m] \033[96;1m• \033[1;37mCHANGE USER LIMIT  \033[96;1m│ $NC"
echo -e " \033[96;1m│ $NC \033[1;37m[\033[96;1m03\033[1;37m] \033[96;1m• \033[1;37mRENEW AKUN       \033[1;37m[\033[96;1m08\033[1;37m] \033[96;1m• \033[1;37mCHANGE USER KUOTA  \033[96;1m│ $NC"
echo -e " \033[96;1m│ $NC \033[1;37m[\033[96;1m04\033[1;37m] \033[96;1m• \033[1;37mDELETE AKUN      \033[1;37m[\033[96;1m09\033[1;37m] \033[96;1m• \033[1;37mLOCK USER          \033[96;1m│ $NC"
echo -e " \033[96;1m│ $NC \033[1;37m[\033[96;1m05\033[1;37m] \033[96;1m• \033[1;37mCEK USER LOGIN   \033[1;37m[\033[96;1m10\033[1;37m] \033[96;1m• \033[1;37mUNLOCK USER        \033[96;1m│ $NC"
echo -e " \033[96;1m│ $NC \033[1;37m[\033[96;1m22\033[1;37m] \033[96;1m• \033[1;37mGANTI UUID        \033[1;37m[\033[96;1m11\033[1;37m] \033[96;1m• \033[1;37mRESTORE AKUN       \033[96;1m│ $NC"
echo -e " \033[96;1m│ $NC \033[1;37m[\033[96;1m00\033[1;37m] \033[96;1m• \033[1;37mKEMBALI
echo -e " \033[96;1m╰════════════════════════════════════════════════════╯"
echo -e " \033[96;1m╭═════════════════════════ \033[1;37mBY${NC} \033[96;1m═══════════════════════╮"
printf "                    \033[96;1m%3s${NC} \033[1;37m%0s${NC} \033[96;1m%3s${NC}\n" "• " "$(cat /etc/xray/username)" " •"
echo -e " \033[96;1m╰════════════════════════════════════════════════════╯"
}

Menu_Features
read -p "Select From Options [0-22] :  " Ltt
case $Ltt in
1) clear ; add-tro ;;
2) clear ; trial-tro ;;
3) clear ; renew-tro ;;
4) clear ; del-tro ;;
5) clear ; cek-tro ;;
6) clear ; check-tro ;;
7) clear ; ganti-ip-trojan ;;
8) clear ; trojan-qouta ;;
9) clear ; lock-tr ;;
10) clear ; unlock-tr ;;
11) clear ; recover-tr ;;
22) clear ; uuidtrojan ;;
00) clear ; menu ;;
*) clear ; m-tro;;
esac
